### ISSUE TITLE
BDTOPO V2

### ISSUE THREAD

**Issue by ML426** [orbisgis/geoclimate#675] opened 2022-02-07 22:05 UTC
Hello, 
I have the following message when I try to use BD TOPO V2.2.
How can I solve this problem?
Thanks
![image](https://user-images.githubusercontent.com/87750674/152879503-e8af930b-8fec-4c63-a5ef-66a8d700d42d.png)

**Comment by j3r3m1** [comment] 2022-02-08 08:34
Hello,
The following informations are necessary to answer easily:
1. copy and paste the content of your configuration file
2. tell us which OS are you using
3. tell us which version of Geoclimate are you using

**Comment by ML426** [comment] 2022-02-08 09:53
**Here is the content of my configuration file**
```
{
    "description": "Processing BDTopo v2 data",
    "input": {"bdtopo_v2":	{
        "folder": {"path": "C:\\GEOCLIMAT\\BDTOPO_2-2",
                   "id_zones":["12174"]}
				}
    },
    "output": {
        "folder": "C:\\temp"
    },
    "parameters": {
        "rsu_indicators": {
            "indicatorUse": [
                "LCZ",
                "TEB",
                 
            ],
            "svfSimplified": true
        },
        "grid_indicators": {
            "x_size": 100,
	    "y_size": 100,
	    "rowCol": false,
	    "output" : "geojson",
	    "indicators" :[
                 "BUILDING_FRACTION", 
                 "BUILDING_HEIGHT", 
                 "WATER_FRACTION",
                 "VEGETATION_FRACTION", 
                 "ROAD_FRACTION", 
                 "IMPERVIOUS_FRACTION", 
                 "LCZ_FRACTION"
             ]
         }
    }
}
```

**I'm using Geoclimate 001 on Windows 10**

**Comment by j3r3m1** [comment] 2022-02-08 12:18
Thanks. Did you double check that your configuration file is in the same folder as your geoclimate .jar ? And that you call the right file name in the console when starting the calculation ?

**Comment by ML426** [comment] 2022-02-08 13:08
Thank,
I think the problem was in the description, in the code on the WIKI : "description": "Processing **BD Topo** v2 data", by changing to **BDTopo** the error disappeared.
But now there is another bug. I have the impression that it can't read the file. (I have downloaded from http://data.cquest.org/ign/bdtopo/ )
![image](https://user-images.githubusercontent.com/87750674/152992477-70ad2de0-fb94-40bd-baff-1fd98f52b6b0.png)

**Comment by ML426** [comment] 2022-02-08 13:24
Is Commune_TMP supposed to be in the folder? or is it created automatically?

**Comment by ebocher** [comment] 2022-02-08 13:42
It seems that GeoClimate is not able to import the COMMUNE.SHP file. 
Commune_TMP is an extraction from COMMUNE.SHP created according the id_zones list.
I will check it asap

**Comment by ML426** [comment] 2022-02-08 13:51
Thanks

**Comment by simogeo** [comment] 2022-02-22 08:43
hello, I have the same problem here, using `geoclimate-0.0.1.jar`

Whatever i use bbox matching or id_zones I get :

```txt
Unsupported file format.
Supported formats are : [csv,dbf,dbf.gz,geojson,geojson.gz,gpx,gpx.gz,osm,osm.gz,osm.bz2,shp,tsv,tsv.gz,asc,asc.gz].
Cannot import the file : /home/68-geoclimate/data/BDTOPO-v2.2/H_ADMINISTRATIF/COMMUNE.SHP
Unable to find table COMMUNE_TMP
The table is not a spatial table.
Error while executing the process.
```

```txt
 java.lang.NullPointerException: Cannot get property 'srid' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60) ~[geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:194) ~[geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:46) ~[geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329) ~[geoclimate-0.0.1.jar:?]
	at org.orbisgis.geoclimate.bdtopo_v2.WorkflowBDTopo_V2.loadDataFromFolder(WorkflowBDTopo_V2.groovy:992) ~[geoclimate-0.0.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351) ~[geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61) ~[geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) ~[geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171) ~[geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203) ~[geoclimate-0.0.1.jar:?]
	at org.orbisgis.geoclimate.bdtopo_v2.WorkflowBDTopo_V2$_workflow_closure1$_closure21.doCall(WorkflowBDTopo_V2.groovy:322) ~[geoclimate-0.0.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[geoclimate-0.0.1.jar:?]
	at groovy.lang.Closure.call(Closure.java:412) ~[geoclimate-0.0.1.jar:?]
	at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300) [geoclimate-0.0.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819) [geoclimate-0.0.1.jar:?]
	at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [geoclimate-0.0.1.jar:?]
	at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy:83) [geoclimate-0.0.1.jar:?]
	at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy) [geoclimate-0.0.1.jar:?]
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933) [geoclimate-0.0.1.jar:?]
	at picocli.CommandLine.access$1200(CommandLine.java:145) [geoclimate-0.0.1.jar:?]
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332) [geoclimate-0.0.1.jar:?]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326) [geoclimate-0.0.1.jar:?]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291) [geoclimate-0.0.1.jar:?]
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159) [geoclimate-0.0.1.jar:?]
	at picocli.CommandLine.execute(CommandLine.java:2058) [geoclimate-0.0.1.jar:?]
	at picocli.CommandLine$execute.call(Unknown Source) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [geoclimate-0.0.1.jar:?]
	at org.orbisgis.geoclimate.Geoclimate.main(Geoclimate.groovy:103) [geoclimate-0.0.1.jar:?]
Cannot execute the BDTOPO_V2.2 workflow
```

**Comment by ebocher** [comment] 2022-02-22 08:57
It seems due to a change in the database utilities H2GIS we used.
You must used geoclimate-0.0.2-snaphot available after each PR : https://github.com/orbisgis/geoclimate/actions/runs/1778005348
as an artifact

**Comment by simogeo** [comment] 2022-02-22 09:40
thanks @ebocher, I didn't know about snapshots being available :+1: 

I'm running into another issue : 

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/orbisgis/geoclimate/Geoclimate has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

i will try to update java !

**Comment by simogeo** [comment] 2022-02-22 09:50
All right ! :+1:

**Comment by ebocher** [comment] 2022-02-22 09:55
Geoclimate needs at least java 11 ;-)

**Comment by ML426** [comment] 2022-02-22 15:04
Thanks @ebocher.
The problems remains.
![image](https://user-images.githubusercontent.com/87750674/155159916-7588da08-358d-4934-931d-24fd45b30c83.png)

**Comment by ebocher** [comment] 2022-03-03 14:44
@ML426  this throwing message is related to OSM. Please share the config file.

**Comment by ebocher** [comment] 2022-03-18 14:06
I am closing this issue as there has been no exchange for several days and I'm not able to reproduce the issue

**Closed by ebocher** 2022-03-18 14:06 UTC
