### ISSUE TITLE
Character encoding problem ?

### ISSUE THREAD

**Issue by syoussou** [orbisgis/geoclimate#659] opened 2021-12-23 09:05 UTC
It seems that there is a problem with some categories of the vegetation layer from the BDTopo. I have identified that categories whose names contain accents, like "forêt fermée de feuillus" or "forêt fermée de conifères" have null height in the output vegetation layer and are identified as LCZ104 instead of LCZ101. Could there be a character encoding problem (utf-8 ...)? Thanks!

**Comment by j3r3m1** [comment] 2021-12-30 14:03
Hi, thank you for reporting.
I had a try in Nantes (insee code 44109) and I could not reproduce the bug.
Could you please tell us:
- which version of GeoClimate you are using
- where did you observe this behaviour (insee code)
-  what do you mean by null height ? (in the resulting vegetation table produced by the workflow, you should have a 'height_class' field which should be either "low" or "high")

**Comment by syoussou** [comment] 2021-12-30 19:09
Hi Jeremy,
Thanks for your comment.

- I use Geoclimate-0.0.1.jar on Windows 10. 
- The study area is Besançon (25056) and several surrounding municipalities. I previously aggregated all these municipalities into a single polygon. 
- In the resulting vegetation table, I have a 'height_class' field with 3 modalities : "high", "low" and "NULL" as you can see in the screenshot1. Most of the vegetation elements are "NULL" as you can see in screenshot2 where I have selected elements where "HEIGHT_CLASS" is null (yellow). I think these elements correspond to those which names contain accents in the input vegetation layer (forêt fermée de feuillus...). It seems that there is no problem with the others like "Haie", "Vigne", "Peupleraie", "Verger", etc.
If you need more information, I'll happy to explain more precisely.

Best regards,

Samy
![01](https://user-images.githubusercontent.com/96570072/147781300-a179dd79-d674-4544-9a33-a917182bb4f8.jpg)
![02](https://user-images.githubusercontent.com/96570072/147781316-6194edaf-322e-43b5-b336-ad42c834f9b7.jpg)

**Comment by j3r3m1** [comment] 2022-01-03 16:49
>     * The study area is Besançon (25056) and several surrounding municipalities. I previously aggregated all these municipalities into a single polygon.

What do you mean by aggregated all municipalities into a single polygon ? Do you use the GeoClimate Workflow as described in the wiki ? If you want to run several communes you add the commune table in the folder where are all your data and then you specify the list of commune (for example "25056" and "25055") you want to process using:
```json
{
    "description": "Processing BD Topo v2 data",
    "input": {"bdtopo_v2":	{
        "folder": {"path": "C:\\mydirectory\\Geoclimate\\BD_TOPO_v2",
                   "id_zones":["25056", "25055"]}
		                }
    },
    "output": {
        "folder": "C:\\temp"
    },
    "parameters": {
        "rsu_indicators": {
            "indicatorUse": [
                "LCZ",
                "TEB",
                "URBAN_TYPOLOGY"
            ],
            "svfSimplified": true
        },
        "grid_indicators": {
            "x_size": 100,
	    "y_size": 100,
	    "rowCol": false,
	    "output" : "geojson",
	    "indicators" :[
                 "BUILDING_FRACTION", 
                 "BUILDING_HEIGHT", 
                 "WATER_FRACTION",
                 "VEGETATION_FRACTION", 
                 "ROAD_FRACTION", 
                 "IMPERVIOUS_FRACTION", 
                 "LCZ_FRACTION"
             ]
         }
    }
}
```
If you make the calculation like that, does it change the results ?

**Comment by syoussou** [comment] 2022-01-03 22:21
Hi,
When I do this, I get this error message:

The  BD Topo data have been imported
Formating the BDTOPO data
Unable to execute the Sql command '
CREATE TABLE BUILD_ZONE_MATRIX__70a3de96_821a_4da3_b09c_f234b6633e96 (ID_BUILD integer primary key, ID_ZONE varchar) AS SELECT * FROM BUILD_WITHIN_ZONE__0cf32ffd_42b6_4b30_8687_f1754dee9a13 UNION SELECT * FROM BUILD_OUTER_ZONE_MATRIX__f50bd61e_d732_4fb6_b72e_761a9fa14c4e'.
Violation d'index unique ou clÚ primaire: "PRIMARY KEY ON PUBLIC.BUILD_ZONE_MATRIX__70A3DE96_821A_4DA3_B09C_F234B6633E96(ID_BUILD) ( /* key:1 */ 1, '25438')"
Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.BUILD_ZONE_MATRIX__70A3DE96_821A_4DA3_B09C_F234B6633E96(ID_BUILD) ( /* key:1 */ 1, '25438')"; SQL statement:

CREATE TABLE BUILD_ZONE_MATRIX__70a3de96_821a_4da3_b09c_f234b6633e96 (ID_BUILD integer primary key, ID_ZONE varchar) AS SELECT * FROM BUILD_WITHIN_ZONE__0cf32ffd_42b6_4b30_8687_f1754dee9a13 UNION SELECT * FROM BUILD_OUTER_ZONE_MATRIX__f50bd61e_d732_4fb6_b72e_761a9fa14c4e [23505-200]
Cannot format the BD Topo data
Cannot format data and compute statistics.
The BDTOPO_V2.2 workflow has been successfully executed

I don't understand why.

Samy

**Comment by j3r3m1** [comment] 2022-01-04 07:27
Hi Samy,
Could you confirm that you use the BDTopo V2.2 ?
If yes, I can have a try, I would just need the insee code you are using (25056 and ?) ?

**Comment by syoussou** [comment] 2022-01-04 08:34
Hi Jeremy,
Yes I use the BDTopo V2.2 (as you can see with the screenshot of the metadata). Here is the list of the municipalities I'm working on. I've just tried again and I have got the same error message. I join you the code I have used to test (with just one municipality).

code_insee
--
25056
25397
25267
25086
25328
25612
25429
25611
25560
25473
25200
25265
25073
25027
25532
25410
25111
25245
25395
25058
25448
25477
25119
25115
25287
25542
25035
25381
25557
25258
25147
25103
25376
25575
25495
25036
25212
25112
25454
25467
25133

{

    "description": "Processing BD Topo v2 data",
    "input": {"bdtopo_v2":	{
        "folder": {"path": "C:\\Users\\syoussoufi\\Geoclimate\\BDTopo",
				   "id_zone":["25056"]}
				}
    },
    "output": {
        "folder": "C:\\Users\\syoussoufi\\Geoclimate\\results"
    },
    "parameters": {
        "rsu_indicators": {
            "indicatorUse": [
                "LCZ",
                "TEB",
                "URBAN_TYPOLOGY"
            ],
            "svfSimplified": true
        },
        "grid_indicators": {
            "x_size": 100,
	        "y_size": 100,
	        "rowCol": false,
	        "output" : "geojson",
	        "indicators" :[
                 "BUILDING_FRACTION", 
                 "BUILDING_HEIGHT", 
                 "WATER_FRACTION",
                 "VEGETATION_FRACTION", 
                 "ROAD_FRACTION", 
                 "IMPERVIOUS_FRACTION", 
                 "LCZ_FRACTION"
             ]
         }
    }
}


![SharedScreenshot](https://user-images.githubusercontent.com/96570072/148030049-82843d84-a308-4221-8067-cfcfdfabcde8.jpg)

**Comment by ebocher** [comment] 2022-03-03 14:45
@syoussou  any input about this issue ?

**Comment by ebocher** [comment] 2022-03-18 14:07
I am closing this issue as there has been no activies for several days.

**Closed by ebocher** 2022-03-18 14:07 UTC
