### ISSUE TITLE
All building indicators

### ISSUE THREAD

**Issue by ntouati** [orbisgis/geoclimate#803] opened 2023-02-07 14:30 UTC
Hi !
I am writing this issue to see if I have understood a point. 
I do have my outputs for the indicator buildings from the BD topo. 
![files](https://user-images.githubusercontent.com/24480303/217272547-c6519be9-537e-4629-9d0f-12bbd8742f38.png)

However, I don't have the following indicators: area_concavity; common_wall_fraction; floor_area etc.
![file2](https://user-images.githubusercontent.com/24480303/217273048-5d0d7be8-e48b-4155-9730-2a69b39314a3.png)

To get these indicators, I have to restart geoclimate with the input of these indicators from my first output?
Thanks for your help.

NT

**Comment by ntouati** [comment] 2023-02-07 15:32
My config file : 

```json{
{
 "description": "Processing BD Topo v2 data",
    "input": {
        "folder":"C:\\Users\\ntouati\\Desktop\\Geoclimate\\BD_TOPO_v2_2",
        "locations":["31149"], 
		"srid" : 2154
		},
    "output": {
        "folder": "C:\\Users\\ntouati\\Desktop\\temp"
    },
    "parameters": {
        "rsu_indicators": {
            "indicatorUse": [
                "LCZ",
                "TEB",
                "URBAN_TYPOLOGY"
            ],
            "svfSimplified": true
        },
        "grid_indicators": {
            "x_size": 100,
	    "y_size": 100,
	    "rowCol": false,
	    "output" : "geojson",
	    "indicators" :[
                 "BUILDING_FRACTION", 
                 "BUILDING_HEIGHT", 
                 "WATER_FRACTION",
                 "VEGETATION_FRACTION", 
                 "ROAD_FRACTION", 
                 "IMPERVIOUS_FRACTION", 
                 "LCZ_FRACTION"
             ]
         }
    }
}```

**Comment by j3r3m1** [comment] 2023-02-07 15:55
When did you download your GeoClimate version ?

**Comment by ntouati** [comment] 2023-02-07 15:57
I used geoclimate-0.0.2-SNAPSHOT.jar

**Comment by lgrll** [comment] 2024-03-19 15:03
Hello, I have the same problem. How can I get all the indicators?

**Comment by j3r3m1** [comment] 2024-03-19 15:39
@ntouati was this problem solved or was it a mistake to close the issue (sorry if it is the case) ?

**Comment by ntouati** [comment] 2024-03-19 15:59
Hi, 
I believe it came from my geoclimate installation. I don't remember very well anymore. Sorry

**Comment by j3r3m1** [comment] 2024-03-19 16:13
Thank you for your prompt reply. But at the end of the day it worked well ?

**Comment by j3r3m1** [comment] 2024-03-19 16:17
> Hello, I have the same problem. How can I get all the indicators?

@lgrll which version of GeoClimate are you using, which config file and which version of BDTopo ?
And what are the files you are getting at the end of the process ? It seems to have a bug with the BDTopo right now but the problem is general, there is no output at all (cf. #945).

**Comment by lgrll** [comment] 2024-03-20 09:02
I use geoclimate-1.0.1-SNAPSHOT.jar and OSM.
I tried with this config file, but I also tried specifying the indicators I wanted and got the same result in output.


{
  "description": "config files FU",
  "geoclimatedb": {
    "folder": "C:\\Users\\lgrll\\Desktop\\Geoclimate",
    "name": "geoclimate_chain_db;AUTO_SERVER=TRUE",
    "delete": true
  },
  "input": {
    "locations": ["Corconne"]
  },
  "output": {
    "folder": "C:\\Users\\lgrll\\Desktop\\Geoclimate"
  },
  "parameters": {
    "rsu_indicators": {
      "indicatorUse": [
        "LCZ"
      ]
    }
  }
}

**Comment by j3r3m1** [comment] 2024-03-21 08:23
Indeed if you want to have the maximum number of indicators, it is better to specify all type of indicator use: "TEB", "LCZ", "UTRF". The config file for that is given in the wiki: https://github.com/orbisgis/geoclimate/wiki/Default-case-with-OSM-for-Linux#create-and-understand-the-configuration-file

**Comment by lgrll** [comment] 2024-03-25 08:46
It works ! Thanks for your help

**Closed** 2024-03-25 09:22 UTC
