### ISSUE TITLE
Groovy version incompatibility

### ISSUE THREAD

**Issue by VakankGrang** [orbisgis/geoclimate#256] opened 2019-12-17 10:01 UTC
Trying to execute the OSM workflow in DBeaver I got an errormessage related to
groovy version incompatibilities. Any idea how to solve this ?

>>>
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Conflicting module versions. Module [groovy-sql is loaded in version 3.0.0-rc-2 and you are trying to load version 2.5.7

groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-sql is loaded in version 3.0.0-rc-2 and you are trying to load version 2.5.7

**Comment by j3r3m1** [comment] 2019-12-17 10:18
@SPalominos do you think that the plug-in should be updated in DBeaver ?

**Comment by SPalominos** [comment] 2019-12-17 13:54
Yes, the DBeaver plugin is often updated and we have recently move to Groovy 3.0.0.

The plugin should be updated using the `help` -> `Install New Software...` menu.
Then on the new window, in the `Work with:` box, select or write `http://devs.orbisgis.org/eclipse-repo`, check the `OrbisGIS` software
Click on `next` (several time) and to finish on `finish`.

Once done, DBeaver will restart you should probably have to clean your `/home/name/.groovy` cache folder to force to redownload the modules (I don't know where it is located on Windows or Mac) before executing a Groovy script.

**Comment by j3r3m1** [comment] 2019-12-18 07:47
> Once done, DBeaver will restart you should probably have to clean your /home/name/.groovy cache folder

Just to be sure it is well interpreted, "clean" means delete the hidden folder .groovy.

**Comment by VakankGrang** [comment] 2019-12-18 08:16
After have done this, I get the following error: 

>>> 

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed: 
General error during conversion: Error grabbing Grapes -- [download failed: net.sourceforge.f2j#arpack_combined_all;0.1!arpack_combined_all.jar, download failed: com.github.fommil.netlib#core;1.1.2!core.jar] 

java.lang.RuntimeException: Error grabbing Grapes -- [download failed: net.sourceforge.f2j#arpack_combined_all;0.1!arpack_combined_all.jar, download failed: com.github.fommil.netlib#core;1.1.2!core.jar] 
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 

Robert 


De: "jeremy-b" <notifications@github.com> 
À: "orbisgis/geoclimate" <geoclimate@noreply.github.com> 
Cc: "VakankGrang" <robert.schoetter@meteo.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 18 Décembre 2019 08:47:06 
Objet: Re: [orbisgis/geoclimate] Groovy version incompatibility (#256) 





Once done, DBeaver will restart you should probably have to clean your /home/name/.groovy cache folder 



Just to be sure it is well interpreted, "clean" means delete the hidden folder .groovy.

**Comment by SPalominos** [comment] 2019-12-18 09:39
I have reproduced the error, and it seems to be linked to the Groovy cache. Did you tried to remove the `.groovy` and `.m2` folders (which should both be located in your `${user.home}\` or `C:\Users\{your-username}\` folder) and rerun the script ?

**Comment by VakankGrang** [comment] 2019-12-18 12:52
After deleting .groovy AND .m2 it works for me.
Thanks.

**Comment by SPalominos** [comment] 2019-12-18 13:30
Great, so I close the issue.

**Closed by SPalominos** 2019-12-18 13:30 UTC
Labels: question
